// Code generated by protoc-gen-go.
// source: proto/spellchecker.proto
// DO NOT EDIT!

/*
Package SpellChecker is a generated protocol buffer package.

It is generated from these files:
	proto/spellchecker.proto

It has these top-level messages:
	Request
	Reply
*/
package SpellChecker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Sentence string `protobuf:"bytes,1,opt,name=sentence" json:"sentence,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

type Reply struct {
	Sentence string `protobuf:"bytes,1,opt,name=sentence" json:"sentence,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reply) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "SpellChecker.Request")
	proto.RegisterType((*Reply)(nil), "SpellChecker.Reply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SpellChecker service

type SpellCheckerClient interface {
	Check(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type spellCheckerClient struct {
	cc *grpc.ClientConn
}

func NewSpellCheckerClient(cc *grpc.ClientConn) SpellCheckerClient {
	return &spellCheckerClient{cc}
}

func (c *spellCheckerClient) Check(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/SpellChecker.SpellChecker/check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SpellChecker service

type SpellCheckerServer interface {
	Check(context.Context, *Request) (*Reply, error)
}

func RegisterSpellCheckerServer(s *grpc.Server, srv SpellCheckerServer) {
	s.RegisterService(&_SpellChecker_serviceDesc, srv)
}

func _SpellChecker_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpellCheckerServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpellChecker.SpellChecker/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpellCheckerServer).Check(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpellChecker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SpellChecker.SpellChecker",
	HandlerType: (*SpellCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "check",
			Handler:    _SpellChecker_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/spellchecker.proto",
}

func init() { proto.RegisterFile("proto/spellchecker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0x48, 0xcd, 0xc9, 0x49, 0xce, 0x48, 0x4d, 0xce, 0x4e, 0x2d, 0xd2, 0x03,
	0x0b, 0x09, 0xf1, 0x04, 0x83, 0xc4, 0x9c, 0x21, 0x62, 0x4a, 0xaa, 0x5c, 0xec, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x52, 0x5c, 0x1c, 0xc5, 0xa9, 0x79, 0x25, 0xa9, 0x79, 0xc9, 0xa9,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x92, 0x32, 0x17, 0x6b, 0x50, 0x6a, 0x41,
	0x4e, 0x25, 0x3e, 0x45, 0x46, 0xae, 0x5c, 0x28, 0x66, 0x0b, 0x99, 0x72, 0xb1, 0x82, 0xad, 0x16,
	0x12, 0xd5, 0x43, 0x16, 0xd7, 0x83, 0x5a, 0x28, 0x25, 0x8c, 0x2e, 0x5c, 0x90, 0x53, 0xa9, 0xc4,
	0x90, 0xc4, 0x06, 0x76, 0xa7, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xf7, 0x54, 0xb1, 0xc3,
	0x00, 0x00, 0x00,
}
